import { SpecialistI } from '@/constants/types';

export const MOCK_SPECIALISTS: SpecialistI[] = [
  {
    id: '1',
    name: 'имя1',
    lastName: 'Фамилия',
    experience: '0 лет',
    quote:
      '«Считаю, что в достижении долгосрочных и эффективных результатов в эстетической медицине большую роль играет междисциплинарный подход»',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '2',
    name: 'имя2',
    lastName: 'Фамилия2',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '3',
    name: 'имя3',
    lastName: 'Фамилия3',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '4',
    name: 'имя4',
    lastName: 'Фамилия4',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '5',
    name: 'имя5',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '6',
    name: 'имя6',
    lastName: 'Фамилия3',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '7',
    name: 'имя7',
    lastName: 'Фамилия4',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '8',
    name: 'имя8',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '9',
    name: 'имя9',
    lastName: 'Фамилия',
    experience: '0 лет',
    quote:
      '«Считаю, что в достижении долгосрочных и эффективных результатов в эстетической медицине большую роль играет междисциплинарный подход»',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '10',
    name: 'имя10',
    lastName: 'Фамилия1',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '12',
    name: 'имя12',
    lastName: 'Фамилия2',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '13',
    name: 'имя13',
    lastName: 'Фамилия3',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '14',
    name: 'имя14',
    lastName: 'Фамилия4',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '15',
    name: 'имя15',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '16',
    name: 'имя16',
    lastName: 'Фамилия3',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '17',
    name: 'имя17',
    lastName: 'Фамилия4',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '18',
    name: 'имя18',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '19',
    name: 'имя19',
    lastName: 'Фамилия4',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '20',
    name: 'имя20',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
  {
    id: '21',
    name: 'имя21',
    lastName: 'Фамилия5',
    experience: '0 лет',
    speciality: 'Главный врач клиники, стаж 10 лет',
    desc: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    imgSrc: '/pages/specialists/list/specialist-foto.png',
  },
];
